### ISSUE TITLE
configure: error: could not find libv8_libplatform library

### ISSUE THREAD

**Issue by tanjhysj0** [phpv8/v8js#346]
I want to install v8js,I have download v8js-2.0.0,my php is 7.1 centos 6.5
when I 
`./configure --with-php-config=/usr/local/php7/bin/php-config --with-v8js`

```
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu
checking for PHP prefix... /usr/local/php7
checking for PHP includes... -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php7/lib/php/extensions/no-debug-non-zts-20160303
checking for PHP installed headers prefix... /usr/local/php7/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... gawk
checking for V8 Javascript Engine... yes, shared
checking for V8 files in default path... found in /usr
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for C standard version... c++0x
checking how to allow c++11 narrowing...
checking for libv8_libplatform... configure: error: could not find libv8_libplatform library

```

**Comment by stesie** [comment]
What's logged in `config.log` file?

**Comment by tanjhysj0** [comment]
config.log:
```
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by configure, which was
generated by GNU Autoconf 2.63.  Invocation command line was

  $ ./configure --with-php-config=/usr/local/php7/bin/php-config --with-v8js

## --------- ##
## Platform. ##
## --------- ##

hostname = centos01
uname -m = i686
uname -r = 2.6.32-431.el6.i686
uname -s = Linux
uname -v = #1 SMP Fri Nov 22 00:26:36 UTC 2013

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = i686
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /sbin
PATH: /bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /root/bin
PATH: /usr/local/mysql/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:1992: checking for grep that handles long lines and -e
configure:2052: result: /bin/grep
configure:2057: checking for egrep
configure:2121: result: /bin/grep -E
configure:2126: checking for a sed that does not truncate output
configure:2180: result: /bin/sed
configure:2317: checking for cc
configure:2333: found /usr/bin/cc
configure:2344: result: cc
configure:2378: checking for C compiler version
configure:2386: cc --version >&5
cc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2390: $? = 0
configure:2397: cc -v >&5
Using built-in specs.
Target: i686-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch=i686 --build=i686-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
configure:2401: $? = 0
configure:2408: cc -V >&5
cc: '-V' option must have argument
configure:2412: $? = 1
configure:2435: checking for C compiler default output file name
configure:2457: cc    conftest.c  >&5
configure:2461: $? = 0
configure:2499: result: a.out
configure:2518: checking whether the C compiler works
configure:2528: ./a.out
configure:2532: $? = 0
configure:2551: result: yes
configure:2558: checking whether we are cross compiling
configure:2560: result: no
configure:2563: checking for suffix of executables
configure:2570: cc -o conftest    conftest.c  >&5
configure:2574: $? = 0
configure:2600: result: 
configure:2606: checking for suffix of object files
configure:2632: cc -c   conftest.c >&5
configure:2636: $? = 0
configure:2661: result: o
configure:2665: checking whether we are using the GNU C compiler
configure:2694: cc -c   conftest.c >&5
configure:2701: $? = 0
configure:2718: result: yes
configure:2727: checking whether cc accepts -g
configure:2757: cc -c -g  conftest.c >&5
configure:2764: $? = 0
configure:2865: result: yes
configure:2882: checking for cc option to accept ISO C89
configure:2956: cc  -c -g -O2  conftest.c >&5
configure:2963: $? = 0
configure:2986: result: none needed
configure:3010: checking how to run the C preprocessor
configure:3050: cc -E  conftest.c
configure:3057: $? = 0
configure:3088: cc -E  conftest.c
conftest.c:8:28: error: ac_nonexistent.h: No such file or directory
configure:3095: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:3128: result: cc -E
configure:3157: cc -E  conftest.c
configure:3164: $? = 0
configure:3195: cc -E  conftest.c
conftest.c:8:28: error: ac_nonexistent.h: No such file or directory
configure:3202: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:3244: checking for icc
configure:3257: result: no
configure:3271: checking for suncc
configure:3284: result: no
configure:3302: checking whether cc understands -c and -o together
configure:3334: cc -c conftest.c -o conftest2.o >&5
configure:3338: $? = 0
configure:3344: cc -c conftest.c -o conftest2.o >&5
configure:3348: $? = 0
configure:3403: result: yes
configure:3419: checking for system library directory
configure:3434: result: lib
configure:3441: checking if compiler supports -R
configure:3470: cc -o conftest -g -O2   conftest.c -R /usr/lib  >&5
cc: unrecognized option '-R'
/usr/lib: file not recognized: Is a directory
collect2: ld returned 1 exit status
configure:3477: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3499: result: no
configure:3504: checking if compiler supports -Wl,-rpath,
configure:3533: cc -o conftest -g -O2   conftest.c -Wl,-rpath,/usr/lib  >&5
configure:3540: $? = 0
configure:3562: result: yes
configure:3611: checking build system type
configure:3629: result: i686-pc-linux-gnu
configure:3651: checking host system type
configure:3666: result: i686-pc-linux-gnu
configure:3688: checking target system type
configure:3703: result: i686-pc-linux-gnu
configure:3812: checking for PHP prefix
configure:3814: result: /usr/local/php7
configure:3816: checking for PHP includes
configure:3818: result: -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib
configure:3820: checking for PHP extension directory
configure:3822: result: /usr/local/php7/lib/php/extensions/no-debug-non-zts-20160303
configure:3824: checking for PHP installed headers prefix
configure:3826: result: /usr/local/php7/include/php
configure:3829: checking if debug is enabled
configure:3859: result: no
configure:3862: checking if zts is enabled
configure:3892: result: no
configure:3963: checking for re2c
configure:3979: found /usr/bin/re2c
configure:3990: result: re2c
configure:3999: checking for re2c version
configure:4013: result: 0.13.5 (ok)
configure:4032: checking for gawk
configure:4049: found /bin/gawk
configure:4060: result: gawk
configure:4107: checking for V8 Javascript Engine
configure:4147: result: yes, shared
configure:4168: checking for V8 files in default path
configure:4173: result: found in /usr
configure:4384: checking for g++
configure:4400: found /usr/bin/g++
configure:4411: result: g++
configure:4438: checking for C++ compiler version
configure:4446: g++ --version >&5
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:4450: $? = 0
configure:4457: g++ -v >&5
Using built-in specs.
Target: i686-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch=i686 --build=i686-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) 
configure:4461: $? = 0
configure:4468: g++ -V >&5
g++: '-V' option must have argument
configure:4472: $? = 1
configure:4475: checking whether we are using the GNU C++ compiler
configure:4504: g++ -c   conftest.cpp >&5
configure:4511: $? = 0
configure:4528: result: yes
configure:4537: checking whether g++ accepts -g
configure:4567: g++ -c -g  conftest.cpp >&5
configure:4574: $? = 0
configure:4675: result: yes
configure:4703: checking how to run the C++ preprocessor
configure:4739: g++ -E  conftest.cpp
configure:4746: $? = 0
configure:4777: g++ -E  conftest.cpp
conftest.cpp:9:28: error: ac_nonexistent.h: No such file or directory
configure:4784: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PHP_V8_EXEC_PATH "/usr/lib/libv8.so"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:4817: result: g++ -E
configure:4846: g++ -E  conftest.cpp
configure:4853: $? = 0
configure:4884: g++ -E  conftest.cpp
conftest.cpp:9:28: error: ac_nonexistent.h: No such file or directory
configure:4891: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PHP_V8_EXEC_PATH "/usr/lib/libv8.so"
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:4946: checking for C standard version
configure:4984: g++ -o conftest -g -O2 -std=c++11  conftest.cpp -lstdc++  >&5
cc1plus: error: unrecognized command line option "-std=c++11"
configure:4988: $? = 1
configure: program exited with status 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PHP_V8_EXEC_PATH "/usr/lib/libv8.so"
| /* end confdefs.h.  */
| int main() { return 0; }
configure:5023: result: c++0x
configure:5026: checking how to allow c++11 narrowing
configure:5068: g++ -o conftest -std=c++0x   conftest.cpp -lstdc++  >&5
configure:5072: $? = 0
configure:5078: ./conftest
configure:5082: $? = 0
configure:5229: result: 
configure:5248: checking for libv8_libplatform
configure:5278: g++ -o conftest -g -O2  -I/usr/include -std=c++0x  -L/usr/lib conftest.cpp -lstdc++   -lv8_libplatform -lv8 >&5
conftest.cpp:10:43: error: libplatform/libplatform.h: No such file or directory
conftest.cpp: In function 'int main()':
conftest.cpp:15: error: 'v8' has not been declared
configure:5285: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PHP_V8_EXEC_PATH "/usr/lib/libv8.so"
| /* end confdefs.h.  */
| 
|       #include <libplatform/libplatform.h>
| 
| int
| main ()
| {
|  v8::platform::CreateDefaultPlatform();
|   ;
|   return 0;
| }
configure:5330: g++ -o conftest -g -O2  -I/usr/include -std=c++0x  -L/usr/lib conftest.cpp -lstdc++   -lv8_libplatform -lv8 -lv8_libbase -lv8_libplatform -lv8 >&5
conftest.cpp:10:43: error: libplatform/libplatform.h: No such file or directory
conftest.cpp: In function 'int main()':
conftest.cpp:15: error: 'v8' has not been declared
configure:5337: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PHP_V8_EXEC_PATH "/usr/lib/libv8.so"
| /* end confdefs.h.  */
| 
|       #include <libplatform/libplatform.h>
| 
| int
| main ()
| {
|  v8::platform::CreateDefaultPlatform();
|   ;
|   return 0;
| }
configure:5356: error: could not find libv8_libplatform library

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=i686-pc-linux-gnu
ac_cv_c_compiler_gnu=yes
ac_cv_cxx_compiler_gnu=yes
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=i686-pc-linux-gnu
ac_cv_objext=o
ac_cv_path_EGREP='/bin/grep -E'
ac_cv_path_GREP=/bin/grep
ac_cv_prog_AWK=gawk
ac_cv_prog_CPP='cc -E'
ac_cv_prog_CXXCPP='g++ -E'
ac_cv_prog_RE2C=re2c
ac_cv_prog_ac_ct_CC=cc
ac_cv_prog_ac_ct_CXX=g++
ac_cv_prog_cc_c89=
ac_cv_prog_cc_cc_c_o=yes
ac_cv_prog_cc_g=yes
ac_cv_prog_cxx_g=yes
ac_cv_target=i686-pc-linux-gnu
ac_cv_v8_cstd=c++0x
ac_cv_v8_narrowing=
lt_cv_path_SED=/bin/sed
php_cv_cc_dashr=no
php_cv_cc_rpath=yes
php_cv_re2c_version='0.13.5 (ok)'

## ----------------- ##
## Output variables. ##
## ----------------- ##

AR=''
AWK='gawk'
CC='cc'
CFLAGS='-g -O2'
CONFIGURE_COMMAND=' '\''./configure'\''  '\''--with-php-config=/usr/local/php7/bin/php-config'\'' '\''--with-v8js'\'''
CONFIGURE_OPTIONS=' '\''--with-php-config=/usr/local/php7/bin/php-config'\'' '\''--with-v8js'\'''
CPP='cc -E'
CPPFLAGS=' -I/usr/include -std=c++0x'
CXX='g++'
CXXCPP='g++ -E'
CXXFLAGS='-g -O2'
DEFS=''
DSYMUTIL=''
ECHO='echo'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/bin/grep -E'
EXEEXT=''
GREP='/bin/grep'
LDFLAGS=' -L/usr/lib'
LIBOBJS=''
LIBS='-lstdc++   -lv8_libplatform -lv8 -lv8_libbase -lv8_libplatform -lv8'
LIBTOOL=''
LN_S=''
LTLIBOBJS=''
NMEDIT=''
OBJEXT='o'
PACKAGE_BUGREPORT=''
PACKAGE_NAME=''
PACKAGE_STRING=''
PACKAGE_TARNAME=''
PACKAGE_VERSION=''
PATH_SEPARATOR=':'
RANLIB=''
RE2C='re2c'
SED='/bin/sed'
SHELL='/bin/sh'
SHLIB_DL_SUFFIX_NAME='so'
SHLIB_SUFFIX_NAME='so'
STRIP=''
ac_ct_CC='cc'
ac_ct_CXX='g++'
bindir='${exec_prefix}/bin'
build='i686-pc-linux-gnu'
build_alias=''
build_cpu='i686'
build_os='linux-gnu'
build_vendor='pc'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE}'
dvidir='${docdir}'
exec_prefix='NONE'
host='i686-pc-linux-gnu'
host_alias='i686-pc-linux-gnu'
host_cpu='i686'
host_os='linux-gnu'
host_vendor='pc'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr/local/php7'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target='i686-pc-linux-gnu'
target_alias=''
target_cpu='i686'
target_os='linux-gnu'
target_vendor='pc'

## ----------- ##
## confdefs.h. ##
## ----------- ##

#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PHP_V8_EXEC_PATH "/usr/lib/libv8.so"

configure: exit 1

```

**Comment by stesie** [comment]
To quote from your config.log file: 

```
conftest.cpp:10:43: error: libplatform/libplatform.h: No such file or directory
```

If you installed V8 correctly (e.g. according to README.Linux.md file) there should be a `/usr/include/libplatform/libplatform.h` file, yet this one is obviously missing.

**Comment by virgofx** [comment]
When using pinepain's PPA, it looks like 6.1, 6.2, 6.3, and 6.4 don't include the `include` directory. 6.0 and 6.5 do. Noticed that can potentially cause an issue.

**Comment by pinepain** [comment]
@virgofx have you installed libv8-X.Y-dev package? It's a one that adds `include` directory to `/opt/libv8-X.Y/include`. I'm not sure about exact syntax, but it should looks something like `phpize && ./configure --with-v8js=/opt/libv8-X.Y/` to pick that specific `libv8` install.

**Comment by virgofx** [comment]
@pinepain You're right .. I somehow forgot to install the `-dev` --- works on all of them with 2.1.0 :)

**Comment by diogoca** [comment]
@tanjhysj0 where did you find `config.log`?

**Comment by uchqur** [comment]
still have error checking for libv8_libplatform... configure: error: could not find libv8_libplatform library
. how do fix?

**Comment by palfaro91** [comment]
same error here using `sudo pecl install v8js`

**Comment by uchqur** [comment]
> same error here using `sudo pecl install v8js`

Thank you Replay. I already fix



install v8js on centos

1. fisrt install php-dev php-pear

2. git this file 
$ git clone https://github.com/dreamfactorysoftware/v8-compiled.git

3. create install folder
$ sudo mkdir /opt/v8

4. copy v8-compiled/ubuntu_16.04/PHP7.1/* all to step 3 create folder
$ sudo cp -Rf 'PWD'/v8-compiled/ubuntu_16.04/PHP7.1/ /opt/v8

5. install V8js 
$ sudo pecl install v8js

7. add v8js to php.ini
$ sudo sh -c 'echo "extension=v8js.so" > /etc/php/7.1/mods-available/v8js.ini'

**Comment by gbidragon** [comment]
![Screen Shot 2020-08-03 at 2 53 22 PM](https://user-images.githubusercontent.com/48518124/89167490-19ee9480-d599-11ea-8abd-85eecb367c7d.png)
I am unable to install PHP V8js on Ubuntu 18.04.4.I am getting the error:
ERROR: `/tmp/pear/temp/v8js/configure --with-php-config=/usr/bin/php-config --with-v8js' failed

I have tried all the approaches shared by you in the ReadMe file .Also as i am new in setting up V8js on Linux Ubuntu .I am facing issues.On Windows i was able to install V8Js as the path was easy to set up.But for Linux it has become tedious.As i am unable to understand the path set up in here as per the steps given.
Please advice

**Comment by gbidragon** [comment]
Also  i tried 
installing the V8js using the below link
https://github.com/phpv8/v8js/blob/php7/README.Linux.md
But every time reach the step for installing 
# Download v8
fetch v8
cd v8

# (optional) If you'd like to build a certain version:
git checkout 6.4.388.18
gclient sync

It throws error
![Screen Shot 2020-08-03 at 3 31 44 PM](https://user-images.githubusercontent.com/48518124/89171537-f62e4d00-d59e-11ea-8b4f-82b588b3307d.png)
Please advice what shall i be doing in regard to the same.
