### ISSUE TITLE
v8js-2.1.0: conftest.cpp:16:2: error: 'CreateDefaultPlatform' is not a member of 'v8::platform'

### ISSUE THREAD

**Issue by jalbstmeijer** [phpv8/v8js#406]
Hi,

Trying to compile v8js-2.1.0 against the latest compiled v8, but also tried v8 7.4.195 on Centos7.

But I keep on getting;
checking for libv8_libplatform... configure: error: could not find libv8_libplatform library

In config.log I find;
conftest.cpp:16:2: error: 'CreateDefaultPlatform' is not a member of 'v8::platform'

Went through all suggestions made in similar reports about missing libv8_libplatform, but have not yet found the solution.

Any suggestion?

Gr, J

[config.log](https://github.com/phpv8/v8js/files/3177520/config.log)

**Comment by jalbstmeijer** [comment]
Hi,

Just tested the same on Fedora 29 as I suspected Centos 7 might just have too old libs and compile tools.
But exactly the same result.

Gr, J

**Comment by jalbstmeijer** [comment]
Tried the v8 compile option: use_custom_libcxx=false

Centos7: results in ./torque: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./torque)
Fedora 29: compiles, but v8js install still gives the same CreateDefaultPlatform error.

**Comment by jalbstmeijer** [comment]
Eventually got it to work.
I don't seem to be a able to compile v8js against the latest v8 version which I get from 'fetch v8'

But doing;
git checkout 6.9.454
gclient sync
(building)

after that it results in a successful compile of v8js-2.1.0 on Centos7 for php72 from scl.
Also tested v8 version 7.0.1, works too.
 
Somewhere between 7.0.1 and the current 7.6.+ it must have broken the compile for v8js.

**Comment by jalbstmeijer** [comment]
found this commit in the php7 branch;
https://github.com/phpv8/v8js/commit/68d2274297823939a527adebf5555014b0a631c6

Tried that checkout against the latest v8, but it fails on something else;

configure:4811: checking for libv8_libplatform
configure:4831: g++ -o conftest -g -O2  -I/opt/v8/include -std=c++11 -lstdc++ -Wl,--rpath=/opt/v8/lib -L/opt/v8/lib conftest.cpp -lstdc++   -lv8_libplatform -lv8 >&5
/tmp/cc34ee0H.o: In function `main':
/tmp/v8js/conftest.cpp:16: undefined reference to `v8::platform::NewDefaultPlatform(int, v8::platform::IdleTaskSupport, v8::platform::InProcessStackDumping, std::unique_ptr<v8::TracingController, std::default_delete<v8::TracingController> >)'
collect2: error: ld returned 1 exit status

**Comment by x3titan** [comment]
I have the same problem

**Comment by WebsliceNL** [comment]
I checked which is the latest v8 version I can compile v8js against;

The last version of v8 on which configure of v8js still works without the "could not find libv8_libplatform library" error is  v8-7.4.138

But then  the compiles fails with;

error: no matching function for call to 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::String>&)'
error: no matching function for call to 'v8::Value::ToObject()'
error: no matching function for call to 'v8::Object::Delete(v8::Local<v8::String>&)'

The last version of v8 on which configure and compile of v8js still works  is  v8-7.0.247

Would be nice if v8js on Centos7 would be able to compile against more recent versions of v8.

**Comment by stesie** [comment]
Please try with v8js version just released (2.1.1), should work with V8 7.5.xx

I don't have Centos around, but works on Ubuntu :)

**Comment by dieisraels** [comment]
v8js release 2.1.1 only works with V8 option "use_custom_libcxx=false". 

But V8 cannot be compiled out of the box under CentOS 7 with "use_custom_libcxx=false" because the standard version of "libstdc++.so" of this distribution is too old and "GLIBCXX" does not contain the required version 3.4.20 or higher. (see: https://github.com/phpv8/v8js/issues/406#issuecomment-492606751).

**Comment by stesie** [comment]
ah, I've overseen your comment above that this is not really a viable option.  Has anyone so far looked into what has to be changed on php-v8js in order to build *without* `use_custom_libcxx=false`?

**Comment by jalbstmeijer** [comment]
Tried v8js-2.1.1 against latest v8 on Centos7; (without use_custom_libcxx=false)

./configure --with-php-config=/opt/remi/php72/root/usr/bin/php-config --with-v8js=/opt/v8 LDFLAGS="-lstdc++"

results in;

configure:4811: checking for libv8_libplatform
configure:4831: g++ -o conftest -g -O2  -I/opt/v8/include -std=c++11 -lstdc++ -Wl,--rpath=/opt/v8/lib -L/opt/v8/lib conftest.cpp -lstdc++   -lv8_libplatform -lv8 >&5
/tmp/ccTIIWTI.o: In function `main':
/tmp/v8js-2.1.1/conftest.cpp:16: undefined reference to `v8::platform::NewDefaultPlatform(int, v8::platform::IdleTaskSupport, v8::platform::InProcessStackDumping, std::unique_ptr<v8::TracingController, std::default_delete<v8::TracingController> >)'
collect2: error: ld returned 1 exit status
configure:4831: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PHP_V8_EXEC_PATH "/opt/v8/lib/libv8.so"
| /* end confdefs.h.  */
| 
|       #include <libplatform/libplatform.h>
| 
| int
| main ()
| {
|  v8::platform::NewDefaultPlatform();
|   ;
|   return 0;
| }

**Comment by asharpe** [comment]
Possibly https://github.com/sactor/v8js/commit/448ec83fc8066b1335537c2de3a76a2f1af3164e ?

**Comment by asharpe** [comment]
I've built v8js 2.1.2 against v8 7.4.288.25 on CentOS 7 with the following patch

```patch
diff --git a/config.m4 b/config.m4
index 2e463b4..70ffe7f 100644
--- a/config.m4
+++ b/config.m4
@@ -93,7 +93,7 @@ if test "$PHP_V8JS" != "no"; then
     save_LIBS="$LIBS"
     LIBS="$LIBS $1 -lv8_libplatform -lv8"
     AC_LINK_IFELSE([AC_LANG_PROGRAM([
-      #include <libplatform/libplatform.h>
+      #include "namespace_hack.h"
     ], [ v8::platform::NewDefaultPlatform(); ])], [
       dnl libv8_libplatform.so found
       AC_MSG_RESULT(found)
diff --git a/v8js_class.cc b/v8js_class.cc
index 4e9be67..190f3ea 100644
--- a/v8js_class.cc
+++ b/v8js_class.cc
@@ -36,6 +36,8 @@ extern "C" {
 #include "zend_exceptions.h"
 }
 
+#include "namespace_hack.h"
+
 #define PHP_V8JS_SCRIPT_RES_NAME "V8Js script"
 
 /* {{{ Class Entries */
diff --git a/v8js_v8.cc b/v8js_v8.cc
index 0730866..a0d6fc4 100644
--- a/v8js_v8.cc
+++ b/v8js_v8.cc
@@ -29,7 +29,7 @@ extern "C" {
 #include "zend_exceptions.h"
 }
 
-#include <libplatform/libplatform.h>
+#include "namespace_hack.h"
 
 
 void v8js_v8_init() /* {{{ */
diff --git a/namespace_hack.h b/namespace_hack.h
new file mode 100644
index 0000000..5dabb0b
--- /dev/null
+++ b/namespace_hack.h
@@ -0,0 +1,30 @@
+#pragma once
+
+/*
+This is an ugly hack to get V8JS GCC build to work with V8 CLANG build:
+- When V8 is built without declaring use_custom_libcxx=false, unique_ptr implementation will
+  end up in std::__Cr namespace
+- However when guilding V8JS, linker searches NewDefaultPlatform implementation using std::unique_ptr,
+  and fails to find one
+- This snippet defines NewDefaultPlatform to match the raw symbol of NewDefaultPlatform with
+  std::__Cr::unique_ptr
+*/
+
+#include <v8.h>
+#include <libplatform/libplatform.h>
+
+namespace v8
+{
+    #define RegisterExtension _ZN2v817RegisterExtensionENSt4__Cr10unique_ptrINS_9ExtensionENS0_14default_deleteIS2_EEEE
+    extern "C" void RegisterExtension(std::unique_ptr<Extension>);
+
+    namespace platform
+    {
+        #define NewDefaultPlatform _ZN2v88platform18NewDefaultPlatformEiNS0_15IdleTaskSupportENS0_21InProcessStackDumpingENSt4__Cr10unique_ptrINS_17TracingControllerENS3_14default_deleteIS5_EEEE
+        extern "C" std::unique_ptr<v8::Platform> NewDefaultPlatform(
+            int thread_pool_size = 0,
+            IdleTaskSupport idle_task_support = IdleTaskSupport::kDisabled,
+            InProcessStackDumping in_process_stack_dumping = InProcessStackDumping::kDisabled,
+            std::unique_ptr<v8::TracingController> tracing_controller = {});
+    }
+}
```

credit to the authors referenced in the comment above for doing the hard yards
