### ISSUE TITLE
V8JS 6.9 no longer builds

### ISSUE THREAD

**Issue by colinmollenhour** [phpv8/v8js#387]
My build using 6.9.360 is failing on the latest php-7 branch with the following error:

```
/bin/bash /tmp/v8js-php7/libtool --mode=compile g++ -Wno-narrowing -std=c++11 -I. -I/tmp/v8js-php7 -DPHP_ATOM_INC -I/tmp/v8js-php7/include -I/tmp/v8js-php7/main -I/tmp/v8js-php7 -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/opt/v8/include -I/opt/v8  -DHAVE_CONFIG_H  -g -O2   -c /tmp/v8js-php7/v8js_methods.cc -o v8js_methods.lo 
 g++ -Wno-narrowing -std=c++11 -I. -I/tmp/v8js-php7 -DPHP_ATOM_INC -I/tmp/v8js-php7/include -I/tmp/v8js-php7/main -I/tmp/v8js-php7 -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/opt/v8/include -I/opt/v8 -DHAVE_CONFIG_H -g -O2 -c /tmp/v8js-php7/v8js_methods.cc  -fPIC -DPIC -o .libs/v8js_methods.o
/tmp/v8js-php7/v8js_methods.cc: In function ‘void v8js_method_require(const v8::FunctionCallbackInfo<v8::Value>&)’:
/tmp/v8js-php7/v8js_methods.cc:528:97: error: no matching function for call to ‘v8::String::Concat(v8::Isolate*&, v8::Local<v8::String>, v8::Local<v8::String>&)’
  source = v8::String::Concat(isolate, V8JS_SYM("(function (exports, module, require) {"), source);
                                                                                                 ^
In file included from /tmp/v8js-php7/php_v8js_macros.h:52:0,
                 from /tmp/v8js-php7/v8js_methods.cc:19:
/opt/v8/include/v8.h:2924:24: note: candidate: static v8::Local<v8::String> v8::String::Concat(v8::Local<v8::String>, v8::Local<v8::String>)
   static Local<String> Concat(Local<String> left, Local<String> right);
                        ^~~~~~
/opt/v8/include/v8.h:2924:24: note:   candidate expects 2 arguments, 3 provided
/tmp/v8js-php7/v8js_methods.cc:529:64: error: no matching function for call to ‘v8::String::Concat(v8::Isolate*&, v8::Local<v8::String>&, v8::Local<v8::String>)’
  source = v8::String::Concat(isolate, source, V8JS_SYM("\n});"));
                                                                ^
```

Looking at the [V8 API Changes](https://docs.google.com/document/d/1g8JFi8T_oAE_7uAri7Njtig7fKaPDfotU6huOa1alds/edit) doc there appears to be some deprecated APIs in 6.9 so not sure if you care to continue to support 6.9 or not but just thought you might want to know either way so the README can be updated with the correct minimum v8 version if not.

**Comment by stesie** [comment]
Thanks for pointing this out, but it already states 6.9.427.18, which is effectively newer than 6.9.360 ... so the real "minimum supported version" should be somewhere in between.  Since both already are out of security support I think it shouldn't matter anyways.
